tradier:
  live:
    url: https://api.tradier.com'
    token: x8d3sxOHfXigaEMumQXE4Yu2tACS
  paper:
    url: https://sandbox.tradier.com
    token: Q7A7WpXgM72XDeW5BKQnKDynUBXx 
iexcloud:
  url:
  token:
alpaca:
  live:
    url:
    token:
  paper:
    url:
    token: